// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "You San Di Technology";
    extern const char* const UnityCopyright = "(c) 2026 You San Di Technology. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/b/o/dev/tj";

    extern const char* const UnityVersion = "2022.3.62t7";
    extern const char* const UnityVersionDigits = "2022.3.62";
    extern const char* const UnityVersionSuffix = "t7";
    extern const UInt32 UnityVersionVer = 2022;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 62;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2022.3.62t7_139712ad4655";
    extern const char* const UnityVersionUnderHash_Verbose = "2022.3.62t7_139712ad4655";
    extern const char* const UnityVersionUnderHash_WithParens = "2022.3.62t7 (139712ad4655)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 1283858;

    extern const UInt64 UnityVersionDate = 1774924119;
    extern const char* const UnityVersionBranch = "tuanjie/1.8/staging";
    extern const char* const UnityVersionDisplay = "2022.3.62t7";
    extern const char* const UnityVersionDisplay_Verbose = "2022.3.62t7.git.1283858";
    extern const char* const UnityVersionRevision = "139712ad4655";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2022.3.62t7 (139712ad4655)";
    extern const wchar_t* const L_UnityVersion = L"2022.3.62t7";


    // Tuanjie version
    extern const char* const TuanjieVersion = "1.8.5";
    extern const char* const TuanjieVersionDigits = "1.8.5";
    extern const char* const TuanjieVersionSuffix = "";
    extern const UInt32 TuanjieVersionVer = 1;
    extern const UInt32 TuanjieVersionMajor = 8;
    extern const UInt32 TuanjieVersionMinor = 5;

    extern const char* const TuanjieVersionUnderHash = "1.8.5_139712ad4655";
    extern const char* const TuanjieVersionUnderHash_Verbose = "1.8.5_139712ad4655";
    extern const char* const TuanjieVersionUnderHash_WithParens = "1.8.5 (139712ad4655)";

    extern const char* const TuanjieVersionDisplay = "1.8.5";
    extern const char* const TuanjieVersionDisplay_Verbose = "1.8.5.git.1283858";

    extern const wchar_t* const L_TuanjieVersionUnderHash_WithParens = L"1.8.5 (139712ad4655)";
    extern const wchar_t* const L_TuanjieVersion = L"1.8.5";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "You San Di Technology"
    #define UNITY_COPYRIGHT "(c) 2026 You San Di Technology. All rights reserved."
    #define UNITY_VERSION_VER 2022
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 62
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2022.3.62t7_139712ad4655"
    #define UNITY_VERSION_PARENS_HASH "2022.3.62t7 (139712ad4655)"
    #define UNITY_VERSION_BLD 1283858
    #define UNITY_VERSION_WIN "2022.3.62.1283858"

    #define TUANJIE_VERSION_VER 1
    #define TUANJIE_VERSION_MAJ 8
    #define TUANJIE_VERSION_MIN 5
    #define TUANJIE_VERSION_UNDER_HASH "1.8.5_139712ad4655"
    #define TUANJIE_VERSION_PARENS_HASH "1.8.5 (139712ad4655)"
    #define TUANJIE_VERSION_WIN "1.8.5.1283858"

#endif // !RC_INVOKED
